version: '3'

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ibot
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      JDBC_DATABASE_URL: jdbc:postgresql://db/ibot
      JDBC_DATABASE_USERNAME: root
      JDBC_DATABASE_PASSWORD: root
    depends_on:
      - db
